version: '3.0'

services:
  db:
    image: mysql:5.7
    ports:
      - '3307:3307'
    environment:
       MYSQL_DATABASE: 'myproject3'
       MYSQL_USER: 'deepak3'
       MYSQL_PASSWORD: '2052'
       MYSQL_ROOT_PASSWORD: '2052'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/GB
    ports:
      - "8000:8000"
    depends_on:
      - db